### ISSUE TITLE
Build fails using Xcode Clang++

### ISSUE THREAD

**Issue by jannismain** [ehabets/Signal-Generator#1]
```
signal_generator.cpp:241:17: error: cannot initialize a variable of type 'const int *'
with an rvalue of type 'const size_t *' (aka 'const unsigned long *')

const int* dim_array      = mxGetDimensions(prhs[3]);
```

Changing `const int *` to `const unsigned long *` allows to build the mex-file.

**Comment by ehabets** [comment]
The type of dim_array_size and dim_array were changed in the latest revision to solve this issue.

**Comment by jannismain** [comment]
latest commit solved all errors and warnings during build!
